version: '0.1.{build}'

clone_depth: 10

environment:
    GitEmail: ci@appveyor.com
    GitAuthor: ci
    GitUsername: mminns
    GitPassword: 
      secure: /GXo1m4yXO8eIbjXBMBOVkC5d05AvG0/+03CmoHZBlsoPp3mnSwDXKLA6CpKNAs3

skip_tags: true

skip_commits:
  author: ci

configuration:
  - Release

image: Visual Studio 2017

platform: Any CPU

before_build:
  - dotnet restore

assembly_info:
  patch: true
  file: SharedAssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-{branch}'

build_script:
  - dotnet build "Itofinity.Appveyor.Refit.sln" ; dotnet pack -p:PackageVersion=$(appveyor_build_version); dotnet publish --runtime win-x64; dotnet publish --runtime linux-x64; dotnet publish --runtime osx-x64; 

artifacts:
  - path: '**\src\**\*.nupkg'
  - path: 'src\Itofinity.Appveyor.Cli\bin\$(configuration)\netcoreapp2.1\win-x64\publish'
    name: apv-cli-v$(appveyor_build_version)-$(configuration)-win-x64
    type: zip
  - path: 'src\Itofinity.Appveyor.Cli\bin\$(configuration)\netcoreapp2.1\linux-x64\publish'
    name: apv-cli-v$(appveyor_build_version)-$(configuration)-linux-x64
    type: zip
  - path: 'src\Itofinity.Appveyor.Cli\bin\$(configuration)\netcoreapp2.1\osx-x64\publish'
    name: apv-cli-v$(appveyor_build_version)-$(configuration)-osx-x64
    type: zip


test_script:
  - dotnet test

cache:
  - packages -> **\packages.config

matrix:
  fast_finish: true

on_success:
  - ps : .\appveyor-tag-repository.ps1

deploy:
  release: mcmw-v$(appveyor_build_version)
  description: 'Mercurial Credential Manager for Windows Release'
  provider: GitHub
  auth_token:
    secure: /GXo1m4yXO8eIbjXBMBOVkC5d05AvG0/+03CmoHZBlsoPp3mnSwDXKLA6CpKNAs3 # your encrypted token from GitHub
  artifact: mcmw-v$(appveyor_build_version)
  draft: false
  prerelease: FALSE
  on:
    branch: master                 # release from master branch only
 