/* 
 * AppVeyor REST API
 *
 * AppVeyor is a hosted continuous integration service which runs on Microsoft Windows.  The AppVeyor REST API provides a RESTful way to interact with the AppVeyor service.  This includes managing projects, builds, deployments, and the teams that build them.  Additional help and discussion of the AppVeyor REST API is available at http://help.appveyor.com/discussions  This Swagger definition is an **unofficial** description of the AppVeyor REST API maintained at https://github.com/kevinoid/appveyor-swagger Please report any issues or suggestions for this Swagger definition at https://github.com/kevinoid/appveyor-swagger/issues/new  #### API Conventions  Fields which are missing from update operations (`PUT` requests) are typically reset to their default values.  So although most fields are not technically required, they should usually be specified in practice. 
 *
 * OpenAPI spec version: 0.20181117.0
 * Contact: team@appveyor.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Itofinity.Appveyor.Refit.Model
{
    /// <summary>
    /// Possible values from `Push-AppveyorArtifact` cmdlet `-Type` parameter.  The web UI only allows selection of `Auto`, `WebDeployPackage`, and unspecified (which it sends as the empty string but functions like omitting the property) for `updateProject`.  Any string can be sent and will be saved/returned, but only these values have a function (as far as I am aware).
    /// </summary>
    /// <value>Possible values from `Push-AppveyorArtifact` cmdlet `-Type` parameter.  The web UI only allows selection of `Auto`, `WebDeployPackage`, and unspecified (which it sends as the empty string but functions like omitting the property) for `updateProject`.  Any string can be sent and will be saved/returned, but only these values have a function (as far as I am aware).</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ArtifactType
    {
        
        /// <summary>
        /// Enum Auto for "Auto"
        /// </summary>
        [EnumMember(Value = "Auto")]
        Auto,
        
        /// <summary>
        /// Enum AzureCloudService for "AzureCloudService"
        /// </summary>
        [EnumMember(Value = "AzureCloudService")]
        AzureCloudService,
        
        /// <summary>
        /// Enum AzureCloudServiceConfig for "AzureCloudServiceConfig"
        /// </summary>
        [EnumMember(Value = "AzureCloudServiceConfig")]
        AzureCloudServiceConfig,
        
        /// <summary>
        /// Enum ElasticBeanstalkPackage for "ElasticBeanstalkPackage"
        /// </summary>
        [EnumMember(Value = "ElasticBeanstalkPackage")]
        ElasticBeanstalkPackage,
        
        /// <summary>
        /// Enum File for "File"
        /// </summary>
        [EnumMember(Value = "File")]
        File,
        
        /// <summary>
        /// Enum NuGetPackage for "NuGetPackage"
        /// </summary>
        [EnumMember(Value = "NuGetPackage")]
        NuGetPackage,
        
        /// <summary>
        /// Enum OctopusPackage for "OctopusPackage"
        /// </summary>
        [EnumMember(Value = "OctopusPackage")]
        OctopusPackage,
        
        /// <summary>
        /// Enum SsdtPackage for "SsdtPackage"
        /// </summary>
        [EnumMember(Value = "SsdtPackage")]
        SsdtPackage,
        
        /// <summary>
        /// Enum WebDeployPackage for "WebDeployPackage"
        /// </summary>
        [EnumMember(Value = "WebDeployPackage")]
        WebDeployPackage,
        
        /// <summary>
        /// Enum Zip for "Zip"
        /// </summary>
        [EnumMember(Value = "Zip")]
        Zip
    }

}
